config/routes.rb
Rails.application.routes.draw do

 root to: 'landing#index'
 resources :lessons, only: [:index, :show]
 resources :vocabularies, only: [:index]

 resources :lessons do
   resources :assessments, only: [:create, :index] do
     get 'take', to: 'assessments#new', on: :member, as: :new
     get 'attempt/:attempt', to: 'assessments#show', on: :member, as: :show
   end
 end

 devise_for :users
 resources :users,  path: "/users", only: [:show]
 authenticated :user do
   root to: 'lessons#index', as: :authenticated_root
 end

 # route for admin
 namespace :admin do
   resources :users
   resources :lessons
   resources :levels
   resources :vocabularies
   resources :assessments
   resources :assessment_questions
   resources :assessment_options
   resources :assessment_answers
   root to: "users#index"
 end

 # route for engine forum
 mount Thredded::Engine => '/forum'
 devise_scope :user do 
   delete '/users/sign_out', to: 'devise/sessions#destroy'
 end
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  has_many :assessment_questions, dependent: :destroy#, :inverse_of => :assessment
  belongs_to :lesson
  has_many :assessment_options
  has_many :assessment_answers
  # has_many :assessment_answers
  # accepts_nested_attributes_for :assessment_questions
  validates :lesson_id, presence: true, allow_nil: false
  validates :attempt_limit, presence: true, allow_nil: false 

  def self.create_assessment
    Lesson.all.each do |lesson|
      Assessment.create(lesson_id: lesson.id, attempt_limit: 10)
    end
  end
end

app/controllers/admin/assessments_controller.rb
module Admin
  class AssessmentsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Assessment.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Assessment.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
 before_action :authenticate_user!

 def index
 end

 def new
  puts "*"*60, params.inspect, "*"*60
  @questions = Assessment.where(lesson_id: params[:lesson_id]).first.assessment_questions
  @attempt_n = getAttemptNumber(Assessment.last.id)

end

def create
    # puts "*"*60, params.inspect
    assessment_id = nil
    assessment_answers = Array.new()

    #Get every question_id and option_id in a hash {question_id => option_id} and the assessment_id
    params.each_pair do |key, value|
      if key.index('assessment_id')
        assessment_id = value.to_i
      elsif key.index('question_id') != nil && value.index('option_id') != nil
        assessment_answers << {key.split('_').last.to_i => value.split('_').last.to_i}
      else
        # puts "ERROR for #{key}=>#{value}"
      end
    end

    #Make sure we found the assessment_id and that at least one answer has been found
    if !(assessment_answers.length > 0) || assessment_id == nil
      # puts "-~#"*20, 'ERROR'
    end

    # Make sure that every answer has been answered (send on error page otherwise with flash)

    option = nil
    question = nil
    
    # Get the current attempt for the assessment
    attempt = nil
    attempt = getAttemptNumber(assessment_id)
    attempt += 1
    # Make sure the attempt isn't exceding the limit
    # if attempt > Assessment.find(assessment_id).attempt_limit
      # redirect_to controller: 'user_assessment_attempts', action: 'attempt_limit'
      # redirect_to controller: 'user_assessment_attempts', action: 'attempt_limit'
    # end

    #Assessment_anwsers is an array, each case contains a hash {question_id => option_id}
    correct = nil
    number_of_correct_answer = 0
    assessment_answers.each do |pair|
      pair.each_pair do |key, value|
        question = AssessmentQuestion.find(key.to_i)
        option = AssessmentOption.find(value.to_i)
      end

      #Raise an error if either question_id or option_id don't exist
      if question == nil || option == nil

      end
      puts "-----------"*10, question.correct_letter, option.letter, '______________'*10
      # Check if the answer is correct
      if option.letter == question.correct_letter
        correct = true
        number_of_correct_answer += 1
      else
        puts 'EEEEEEEEEEELLLLLLLLLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEE'
        correct = false
      end
      puts correct

      #Prepare to catch exeception if an error occurs during the entry creation
      begin
        AssessmentAnswer.create!(
          letter: option.letter,
          answer: option.answer,
          attempt_number: attempt,
          correct: correct,
          assessment_question_id: question.id,
          assessment_id: assessment_id,
          user_id: current_user.id
          )
      rescue ActiveRecord::RecordInvalid => e
        puts "Error: #{e}", correct
      end

    end
      # Create result entry
      number_of_questions = assessment_answers.length
      score =  ((number_of_correct_answer.to_f / number_of_questions.to_f) * 100).to_i
      puts "#"*20, number_of_correct_answer, number_of_questions, score
      is_past = false
      score >= 80 ? is_past = true : false
      begin
        Result.create!(is_past?: is_past, score: score, date_exam: Date.today, lesson_id: params[:lesson_id], user_id: current_user.id)
      rescue ActiveRecord::RecordInvalid => e
        puts "Error: #{e}", correct
      end

    # redirect_to 'user_assessment_attempt#show' with proper parameters to display the results
    redirect_to controller: 'assessments', action: 'show', lesson_id: Assessment.find(assessment_id).lesson.id, id: assessment_id, attempt: attempt
  end

  def show
    # Make sure the user passed the test he is trying to view

    # Get the attempt number
    @attempt = getAttemptNumber(params[:id])

    # Get the correct assessment
    assessment = Assessment.find(params[:id])
    # Get the correct assessments questions
    @questions = assessment.assessment_questions

    # Get the correct options (actually useless)
    # @options = Array.new()
    # @questions.each do |question|
    #   @options << question.assessments_options
    # end

    # Get the correct answers
    @answers = AssessmentAnswer.where(assessment_id: params[:id], user_id: current_user.id, attempt_number: params[:attempt])
    puts "#"*20, @answers ,"#-"*20
    

  end

  private

  # def attempt_limit 
  # end

  #Make it a helper
  def getAttemptNumber(assessment_id)
    # puts "-*"*20, "attempt"
    assessments_answers = AssessmentAnswer.where(user_id: current_user.id, assessment_id: assessment_id)
    if assessments_answers != nil && assessments_answers.length > 0
      assessments_answers = assessments_answers.order(attempt_number: :desc)
      if assessments_answers.first.attempt_number != nil
        assessments_answers.first.attempt_number
      else
        0
      end
    else
      # puts "Assessment_answer is nil"
      0
    end
  end

end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/views/assessments/assessment_limit.html.erb
<p>Oups looks like you've reached the limit for this assessment</p>

app/views/assessments/assessment_unavailable.html.erb
<p>Oups on dirait que vous n'avez pas encore passé ce test</p>

app/views/assessments/create.html.erb
<p>create</p>

app/views/assessments/new.html.erb
<% if @questions != nil %>
<div class="container border">
	<form action='<%= lesson_assessments_path %>' method="post">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
		<input type='hidden' value='<%= @questions.first.assessment.id %>' name='assessment_id_<%= @questions.first.assessment.id %>'>
		<% @questions.each do |question| %>
		<h4><%= question.question %> (correct answer is : <%= question.correct_letter %> : <%= question.correct_answer %>)</h4>
		<label hidden for='question_id_<%= question.id %>'></label>
		<% if question.assessment_options.length > 0 %>
		<div class='list-group'>
			<% question.assessment_options.each do |option| %>
			<a class='list-group-item list-group-item-action'>
				<%= option.letter %> <%= option.answer %><input type='radio' name='question_id_<%= question.id %>' value='option_id_<%= option.id %>' id='option_id_<%= option.id %>' required="required">
			</a>
			<% end %>
		</div>
		<% end %>
		<% end %>
		<input type='submit' value='Envoyer !' class='btn btn-success mb-3'>
	</form>
</div>
<% else %>
<p>Oups on dirait que vous avez atteri ici par erreur :(</p>
<% end %>


<%= javascript_include_tag 'assessment_new.js', type: 'text/javascript'%>

app/views/assessments/show.html.erb
<%= stylesheet_link_tag 'assessment_show.css', type: 'text/css'%>

<% if @questions != nil %>
<div class="container border">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
	<input type='hidden' value='<%= @questions.first.assessment.id %>' name='assessment_id_<%= @questions.first.assessment.id %>'>
	<% @questions.each do |question| %>
	<h4><%= question.question %> (correct answer is : <%= question.correct_letter %> : <%= question.correct_answer %>)</h4>
	<label hidden for='question_id_<%= question.id %>'></label>
	<% if question.assessment_options.length > 0 %>
	<div class='list-group borderless m-2 mb-0'>
		<% question.assessment_options.each do |option| %>
		<% current_answer = @answers.find_by(assessment_question_id: question.id) %>
		<% correct_and_selected = false %>
		<% incorrect = false %>
		<% correct_but_not_selected = false %>
		<% if current_answer.answer == option.answer && current_answer.correct%>
		<% correct_and_selected = true %>
		<% elsif current_answer.answer == option.answer && !current_answer.correct%>
		<% incorrect = true %>
		<% end %>
		<% if question.correct_answer == option.answer && !current_answer.correct %>
		<% correct_but_not_selected = true %>
		<% end %>
		<div class="list-group-item
		<%= 'correct' if correct_and_selected -%>
		<%= 'incorrect' if incorrect -%>
		<%= 'correct_but_not_selected' if correct_but_not_selected -%>">
		<%= option.letter -%> <%= option.answer -%></div>
		<% end %>
	</div>
	<% end %>
	<% end %>
</div>
<% else %>
<p>Oups on dirait que vous avez atteri ici par erreur :(</p>
	<% end %>

app/views/assessments/unauthorized.html.erb
<p>Oups on dirait que vous n'avez pas encore le droit d'être ici</p>