config/routes.rb
Rails.application.routes.draw do

 root to: 'landing#index'
 resources :lessons, only: [:index, :show]
 resources :vocabularies, only: [:index]

 resources :lessons do
   resources :assessments, only: [:create, :index] do
     get 'take', to: 'assessments#new', on: :member, as: :new
     get 'attempt/:attempt', to: 'assessments#show', on: :member, as: :show
   end
 end

 devise_for :users
 resources :users,  path: "/users", only: [:show]
 authenticated :user do
   root to: 'lessons#index', as: :authenticated_root
 end

 # route for admin
 namespace :admin do
   resources :users
   resources :lessons
   resources :levels
   resources :vocabularies
   resources :assessments
   resources :assessment_questions
   resources :assessment_options
   resources :assessment_answers
   root to: "users#index"
 end

 # route for engine forum
 mount Thredded::Engine => '/forum'
 devise_scope :user do 
   delete '/users/sign_out', to: 'devise/sessions#destroy'
 end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :level
  has_many :vocabularies
  has_many :results
  has_many :assessments

  validates :order, presence: true
  validates :title, presence: true
  validates :script, presence: true
  validates :grammar, presence: true
  validates :description, presence: true
  # validates :media, presence: true
end

app/controllers/admin/lessons_controller.rb
module Admin
  class LessonsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Lesson.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Lesson.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  # layout false, only: [:index]
  before_action :authenticate_user!

  def index
    @lessons = Lesson.all
    @levels = Level.all
  end

  def show
    @lesson = Lesson.find(params[:id])
    @assessment = Assessment.find_by(lesson_id: params[:id])
    if @assessment != nil
      @assessment_attempts = Array.new()
      @number_of_attempts = getAttemptNumber(@assessment.id)    
      for i in (1..@number_of_attempts)
        @assessment_attempts << @assessment.assessment_answers.where(user_id: current_user.id, attempt_number: i)
      end
    end
  end

  private

  #Make it a helper
  def getAttemptNumber(assessment_id)
    assessments_answers = AssessmentAnswer.where(user_id: current_user.id, assessment_id: assessment_id)
    if assessments_answers != nil && assessments_answers.length > 0
      assessments_answers = assessments_answers.order(attempt_number: :desc)
      if assessments_answers.first.attempt_number != nil
        assessments_answers.first.attempt_number
      else
        0
      end
    else
      # puts "Assessment_answer is nil"
      0
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form_registration.html.erb
              <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
                <%= render "devise/shared/error_messages", resource: resource %>

                <div class="form-control form-control-xl mb-4">
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <p><%= f.label :first_name %><br />
                          <%= f.text_field :first_name %></p>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <p><%= f.label :last_name %><br />
                          <%= f.text_field :last_name %></p>
                      </div>
                    </div>
                  </div>

                  <p><%= f.label :date_of_birth %><br />
                  <%= f.text_field :date_of_birth, autofocus: true, autocomplete: "date_of_birth", "data-provide" => 'datepicker', class: "form-control form-control-lg datepicker" %></p><br />

                  <div class="col-md-6">
                    <div class="form-group">
                      <%= f.radio_button :gender, 'female', :checked => true %>
                      <%= label :gender, 'Female' %>
                      <%= f.radio_button :gender, 'male' %>
                      <%= label :gender, 'Male' %>
                    </div>
                  </div>

                  <div class="form-group">
                    <%if @user.avatar.attached?%>
                      <%= image_tag @user.avatar, alt: 'avatar', height: 80, width: 80, class: 'rounded-circle' %>
                      <%= f.file_field :avatar, id: "file-4", class: "custom-input-file custom-input-file--4" %>
                    <%else%>
                      <p>No avatar</p>
                      <%= f.file_field :avatar, id: "file-4", class: "custom-input-file custom-input-file--4" %>
                    <%end%>
                    <label for="file-4">
                            <span></span>
                            <strong>
                                <i class="fa fa-upload"></i>
                                Choose a file…
                            </strong>
                    </label>
                  </div>

                <div class="field">
                  <%= f.label :email %><br />
                  <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
                </div>

                <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
                  <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
                <% end %>

                <div class="field">
                  <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
                  <%= f.password_field :password, autocomplete: "new-password" %>
                  <% if @minimum_password_length %>
                    <br />
                    <em><%= @minimum_password_length %> characters minimum</em>
                  <% end %>
                </div>

                <div class="field">
                  <%= f.label :password_confirmation %><br />
                  <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
                </div>

                <div class="field">
                  <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
                  <%= f.password_field :current_password, autocomplete: "current-password" %>
                </div>

                <div class="actions">
                  <%= f.submit "Update", class: "btn btn-styled  btn-base-1 mt-4"  %>
                </div>
              <% end %>

app/views/lessons/index.html.erb
<div class="section-title section-title--style-2 text-center mb-4">
  <h3 class="section-title-inner heading-2 strong-400">
    <span>My Courses</span>
  </h3>
  <section class="slice sct-color-1">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <div class="text-center">
            <div class="heading heading-2 strong-600 line-height-1_8">
              Are you ready to improve your French ?
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- CHOISIR AFFICHAGE NIVEAU -->

<%= javascript_include_tag 'level_buttons'%>

  <section class="sct-color-1">
    <div class="container">
      <div class="masonry-filter-menu link-menu link-menu--style-3 text-center">
        <%= link_to "Show all", 'javascript:;', id: "levelAll", class: 'btn-filter default' %>
        <% @levels.each do |level| %>
        <%= link_to "#{level.niveau} #{level.level_description}", 'javascript:;', id: "level#{level.niveau}" ,class: 'btn-filter' %>
        <% end %>
       </div>
     </div>

     <div class="container mt-5">
      <span class="delimiter delimiter--style-1"></span>
    </div>
  </section>

  <% @levels.order(niveau: :asc).each do |current_level| %>
  <% lessons_array = @lessons.select {|lesson| lesson.level == current_level} %>
  <div class="level<%= current_level.niveau %>">
    <div class="col-wrapper--spaced text-center animate-on-scroll fadeInDown">
      <div class="btn btn-base-4" style="pointer-events: none"><%= current_level.niveau %> <%= current_level.level_description %></div>
    </div>
    <section class="sct-color-1" id="sct_timeline" data-cat="level<%= current_level.niveau %>">
      <div class="container">
        <div class="timeline">
          <% lessons_array.each do |lesson| %>
          <div class="timeline-block">
            <span class="timeline-img"></span>
            <div class="timeline-content border-0">

              <div class="icon-block icon-block--style-2-v2 text-center">
                <%=  link_to lesson_path(lesson.id) do %>
                  <div class='block-icon rounded'>
                    <i class='<%= lesson.icone%>'> </i>
                  </div>
                  <div class="row justify-content-center">
                  <h2 class="heading heading-6 strong-600 col-6"><%= lesson.title %></h2>
                  </div>
                <% end %>
                <p class="px-2">
                </p>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </section>
  </div>
  <% end %>

app/views/lessons/show.html.erb
<!-- LESSON NAME -->
<div class="section-title section-title--style-1 text-center mb-2">
  <h3 class="section-title-inner text-normal mt-5">
    <span><%= @lesson.level.niveau %>, LEÇON <%= @lesson.order %></span>
  </h3>
  <h4><%= @lesson.title %></h4>

  <span class="section-title-delimiter clearfix d-none"></span>
</div>

<span class="clearfix"></span>

<div class="fluid-paragraph text-center">
  <p class="text-lg line-height-1_8 c-gray-light strong-300">
    <i class="fas fa-crosshairs"></i>
    <%= @lesson.description %>
  </p>
</div>

<section class="slice sct-color-1">

  <!-- BLOCK IMAGE -->
  <div class="container">
    <div class="col lg-12 mb-3">
      <div class="row row justify-content-between">
        <div class="col-lg-5 mb-5">
          <div class="block block-image-holder">
            <div class="block-image">
              <% if @lesson.media != nil %>
              <%= image_tag(@lesson.media, alt: 'media',  class: "img-fluid img-center") %>
              <%else%>
                <%= image_tag("https://images.unsplash.com/photo-1494249465471-5655b7878482?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80", class: "img-fluid img-center") %>
              <% end %>
            </div>
          </div>
        </div>

        <!-- BLOCK SCRIPT -->
        <div class="col-md-7 col-sm-12">
          <div class="feature feature--boxed-border feature--bg-1">
            <div class="icon-block icon-block--style-1-v2">
              <div class="block-icon text-xs-left">
                <i class="fas fa-book-reader"></i>
              </div>
              <div class="block-content">
                <h3 class="heading heading-4 strong-600">

                SCRIPT</h3>

                <p style="white-space: pre-line"><%= @lesson.script %></p>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- BLOCK GRAMMAIRE -->

    <div class="col-md-12 col-sm-12 mb-5">
      <div class="feature feature--boxed-border feature--bg-1">
        <div class="icon-block icon-block--style-1-v2">
          <div class="block-icon text-xs-left">
            <i class="fas fa-chalkboard-teacher"></i>
          </div>
          <div class="block-content">
            <h3 class="heading heading-4 strong-600">

            GRAMMAR</h3>
              <p style="white-space: pre-line"><%= @lesson.grammar %></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- IMAGE BLOCK 2 -->

  <div class="container">
    <div class="col lg-12 mb-3">
      <div class="row row justify-content-between">

        <!-- VOCABULARY BLOCK -->
        <div class="col-md-7 col-sm-12">
          <div class="feature feature--boxed-border feature--bg-1">
            <div class="icon-block icon-block--style-1-v2">
              <div class="block-icon text-xs-left">
                <i class="fas fa-sort-alpha-up"></i>
              </div>

              <div class="block-content">
                <h3 class="heading heading-4 strong-600">

                VOCABULARY</h3>
                <p>
                  <% @lesson.vocabularies.each do |vocabulary| %>
                  <%= vocabulary.word %> = <%= vocabulary.traduction %><br>
                  <% end %>
                </p>

              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-5 mb-5">
          <div class="block block-image-holder">
            <div class="block-image">
              <% if @lesson.media2 != nil %>
              <%= image_tag(@lesson.media2, alt: 'media',  class: "img-fluid img-center") %>
              <%else%>
                <%= image_tag("https://images.unsplash.com/photo-1543332164-6e82f355badc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80", class: "img-fluid img-center") %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

  </section>
  <section class='container'>
    <p>
      <% if @lesson.assessments.length > 0 %>
      <% if @number_of_attempts == 0 || @number_of_attempts == nil%>
      Vous n'avez pas encore passé ce test
      <% else %>
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Vous avez passé ce test <%= @number_of_attempts %> fois.
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% @assessment_attempts.each do |attempt| %>
          <%= link_to "Visualiser l'essai n°#{attempt.first.attempt_number}", show_lesson_assessment_path(attempt.first.assessment.lesson.id, attempt.first.assessment.id, attempt.first.attempt_number), class: 'dropdown-item' %>
          <% end %>
          </div>
        </div>
        <% end %>
      </p>
      <%= link_to "Passer le test", new_lesson_assessment_path(@lesson.id, @lesson.assessments.first.id), class: 'btn btn-success' %>
      <% else %>
      Aucun test n'est disponible pour cette leçon.
      <% end %>
    </section>