config/routes.rb
Rails.application.routes.draw do

 root to: 'landing#index'
 resources :lessons, only: [:index, :show]
 resources :vocabularies, only: [:index]

 resources :lessons do
   resources :assessments, only: [:create, :index] do
     get 'take', to: 'assessments#new', on: :member, as: :new
     get 'attempt/:attempt', to: 'assessments#show', on: :member, as: :show
   end
 end

 devise_for :users
 resources :users,  path: "/users", only: [:show]
 authenticated :user do
   root to: 'lessons#index', as: :authenticated_root
 end

 # route for admin
 namespace :admin do
   resources :users
   resources :lessons
   resources :levels
   resources :vocabularies
   resources :assessments
   resources :assessment_questions
   resources :assessment_options
   resources :assessment_answers
   root to: "users#index"
 end

 # route for engine forum
 mount Thredded::Engine => '/forum'
 devise_scope :user do 
   delete '/users/sign_out', to: 'devise/sessions#destroy'
 end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
<% if key == 'notice' || key == 'success' %>
  <div class="alert alert-success alert-dismissable" role="alert">
<% elsif key == 'alert' || key == 'danger'%>
  <div class="alert alert-danger">
    <% else %>
      <div class="alert alert-<%= key %>">
    <% end %>
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer" class="footer static-bottom">
	<div class="footer-bottom py-4">
		<div class="container">
			<div class="row cols-xs-space col-sm-space align-items-center">
				<div class="col-lg-3 col-12">
					<div class="text-center text-lg-left">
						<div class="copyright">
							<ul class="copy-links no-margin">
								<li>
										&copy; 2019 Bibimbapp
								</li>
							</ul>
						</div>
					</div>
			</div>

			<div class="col-lg-6">
					<div class="text-center">
						<ul class="footer-menu footer-menu-sm">
							<li>
								<%= mail_to "mailto:bibimpbapp@gmail.com", "Contact us", subject: "Hi Bibimbapp", style: "padding-left: 0;"%>
							</li>
							<li>
								<%= link_to 'Forum', thredded_path, target: "_blank", style: "padding-left: 0;"%>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <%=link_to image_tag( 'logo/bibimbapp-dark.png', id:"logo", class: "img-responsive", alt: ""), user_signed_in? ? lessons_path : root_path  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="fa fa-bars fa-2" style=""></span>
  </button>


  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav m-auto">

      <li class="nav-item ">
        <%= link_to 'Courses', lessons_path, class: "nav-link" %>
      </li>
      <li class="nav-item ">
        <%= link_to 'Vocabulary', vocabularies_path, class: "nav-link" %>
      </li>
      <li class="nav-item ">
        <%= link_to 'Forum', thredded_path, target: "_blank", class: "nav-link" %>
      </li>
      <li class="nav-item ">
      <% if user_signed_in? %>
        <%= link_to 'My stats', user_path(current_user.id), class: "nav-link" %>
      <%end%>
      </li>

    </ul>

    <div class="dropdown" style="padding-right: 20px">
      <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <% if user_signed_in? && current_user.avatar != nil %>
        <%= image_tag(current_user.avatar , alt: 'avatar', height: 50, width: 50, class: 'rounded-circle') if current_user.avatar.attached?  %>
        <%= current_user.first_name %> <%= current_user.last_name %>
        <% elsif user_signed_in? %>
        <%= current_user.first_name %> <%= current_user.last_name %>
        <%else%>
        Sign in/Sign up
        <% end %>
      </button>

      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <% if user_signed_in? %>
          <% if user_signed_in? && current_user.is_admin? %>
            <%= link_to 'Administration', admin_root_path, class: "dropdown-item text-danger", target: "_blank" %>
          <div class="dropdown-divider" role="presentation"></div>
          <% end %>
          <%= link_to 'Profile', user_path(current_user.id), class: "dropdown-item" %>
          <div class="dropdown-divider" role="presentation"></div>
          <%= link_to 'Logout', destroy_user_session_path, class: "dropdown-item" %>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: "dropdown-item" %>
          <%= link_to 'Login', new_user_session_path, class: "dropdown-item" %>
        <% end %>
      </div>
    </div>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bibimbapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application.css', type: 'text/css'%>
    <%= javascript_include_tag 'application.js', type: 'text/javascript'%>

    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800|Roboto:400,500,700" rel="stylesheet">
    <script src="https://kit.fontawesome.com/bf77c3f20d.js"></script>
    <link rel="icon" type="image/png" href="<%= asset_path('presentation/favicon.png')%>" />
  </head>
    <body>
      <div class="head">
        <%= render 'layouts/header' %>
        <%= render 'layouts/flash'%>
      </div>
      <div class="site-content">
        <%= yield %>
      </div>
      <div class="foot">
        <%= render 'layouts/footer'%>
      </div>
  </body>
</html>